In [148]:
import numpy as np

# Definir estados, acciones y recompensas
estados = ['A', 'B', 'C', 'D', 'E']
acciones = ['izquierda', 'derecha']
recompensas = np.array([
    [0, -1],
    [1, 0],
    [-1, 1],
    [1, 0],
    [-1, 0]
])

# Inicializar la matriz Q con ceros
Q = np.zeros((len(estados), len(acciones)))

# Parámetros del algoritmo
gamma = 0.9  # Tasa de descuento
alpha = 0.5  # Tasa de aprendizaje (reducida para convergencia más lenta pero más estable)
epsilon = 0.9  # Probabilidad de exploración

# Ejecutar el algoritmo Q-learning
num_episodes = 1000
for episode in range(num_episodes):
    # Inicializar el estado de manera aleatoria
    estado = np.random.randint(0, len(estados))

    while True:
        # Selección de acción: exploración o explotación
        if np.random.rand() < epsilon:
            accion = np.random.randint(0, len(acciones))
        else:
            accion = np.argmax(Q[estado])

        # Obtener la recompensa y el próximo estado según la acción tomada
        recompensa = recompensas[estado, accion]
        proximo_estado = (estado + 1) % len(estados)

        # Actualizar la matriz Q con la fórmula de Q-learning
        Q[estado, accion] = Q[estado, accion] + alpha * (recompensa + gamma * np.max(Q[proximo_estado, :]) - Q[estado, accion])

        # Actualizar el estado al próximo estado
        estado = proximo_estado

        # Si se alcanza el estado final (A), terminar el episodio
        if estado == 0:
            break

# Imprimir la matriz Q resultante
print("Matriz Q:")
print(Q)

Matriz Q:
[[5.95583508 4.95582211]
 [6.6176019  5.61758817]
 [4.24178174 6.24178935]
 [5.82421986 4.82421555]
 [4.36024782 5.36025092]]


# Aqui se podra observar las probabilidades y la accion que se toma segun a la probabilidad mas alta

In [149]:
# Imprimir la matriz Q resultante del algoritmo Q-learning
print("Matriz Q:")
print(Q)
# Calcular las probabilidades de cada acción en cada estado utilizando la función softmax
probs = np.exp(Q) / np.sum(np.exp(Q), axis=1, keepdims=True)
# Obtener el índice de la acción con mayor y menor probabilidad en cada fila
acciones_maximas = np.argmax(probs, axis=1)
acciones_minimas = np.argmin(probs, axis=1)
# Redondear las probabilidades a un decimal y mostrarlas como porcentajes
probabilidades_acciones = np.round(probs * 100, 1)
# Iterar a través de cada estado y mostrar las probabilidades y la acción con mayor probabilidad
for estado, acciones_probabilidades, accion_maxima in zip(estados, probabilidades_acciones, acciones_maximas):
    print(f"\n Estado {estado}:")
    # Iterar a través de cada acción en el estado y mostrar la probabilidad
    for accion, probabilidad in zip(acciones, acciones_probabilidades):
        print(f"  Probabilidad para la acción {accion}: {probabilidad:.1f}%")
    # Imprimir líneas separadoras
    print("#" * 25)
    # Mostrar la acción con la probabilidad máxima como el camino a tomar en ese estado
    print(f"  Camino a tomar: {acciones[accion_maxima]}")
    # Imprimir líneas separadoras
    print("#" * 25)


Matriz Q:
[[5.95583508 4.95582211]
 [6.6176019  5.61758817]
 [4.24178174 6.24178935]
 [5.82421986 4.82421555]
 [4.36024782 5.36025092]]

 Estado A:
  Probabilidad para la acción izquierda: 73.1%
  Probabilidad para la acción derecha: 26.9%
#########################
  Camino a tomar: izquierda
#########################

 Estado B:
  Probabilidad para la acción izquierda: 73.1%
  Probabilidad para la acción derecha: 26.9%
#########################
  Camino a tomar: izquierda
#########################

 Estado C:
  Probabilidad para la acción izquierda: 11.9%
  Probabilidad para la acción derecha: 88.1%
#########################
  Camino a tomar: derecha
#########################

 Estado D:
  Probabilidad para la acción izquierda: 73.1%
  Probabilidad para la acción derecha: 26.9%
#########################
  Camino a tomar: izquierda
#########################

 Estado E:
  Probabilidad para la acción izquierda: 26.9%
  Probabilidad para la acción derecha: 73.1%
#########################


# **Una vez entrenado el modelo aqui podemos utilizar colocando el estado que desamos y lo muestra correctamente porque el modelo ya esta entrenado**

In [150]:
# Imprimir la matriz Q resultante del algoritmo Q-learning
print("\nMatriz Q:")
print(Q)

# Utilizar la política aprendida para tomar decisiones
def tomar_decision(estado):
    return np.argmax(Q[estado])

# Ejemplo de uso
estado_inicial = 3  # Puedes cambiar esto con el estado desde el que quieres empezar
print(f"\nTomar decisiones desde el estado {estados[estado_inicial]}:")

# Tomar decisiones durante 5 pasos
for _ in range(5):
    accion_elegida = tomar_decision(estado_inicial) # Obtener la acción elegida utilizando la política aprendida
    print(f"Desde {estados[estado_inicial]}, tomar acción: {acciones[accion_elegida]}")  # Imprimir la acción elegida desde el estado actual
    # Actualizar el estado al próximo estado
    estado_inicial = (estado_inicial + 1) % len(estados)



Matriz Q:
[[5.95583508 4.95582211]
 [6.6176019  5.61758817]
 [4.24178174 6.24178935]
 [5.82421986 4.82421555]
 [4.36024782 5.36025092]]

Tomar decisiones desde el estado D:
Desde D, tomar acción: izquierda
Desde E, tomar acción: derecha
Desde A, tomar acción: izquierda
Desde B, tomar acción: izquierda
Desde C, tomar acción: derecha


In [151]:
import numpy as np

# Definir los estados y acciones
estados = ['A', 'B', 'C', 'D','E']
acciones = ['column 1', 'column 2', 'column 3', 'column 4']   #'column 1', 'column 2', 'column 3', 'column 4'

# Definir la matriz de recompensas
recompensas = np.array([
    [1, 1, 0, 0],
    [1, -1, 0, -1],
    [0, 1, -1, 0],
    [0, 1, 1, -1],
    [-1, 0, 1, 0]
])

# Inicializar la matriz Q con ceros
Q = np.zeros((len(estados), len(acciones)))

# Hiperparámetros
gamma = 0.9  # Tasa de descuento
alpha = 0.5  # Tasa de aprendizaje
epsilon = 0.9  # Probabilidad de exploración

# Ejecutar el algoritmo Q-learning
num_episodes = 100
for episode in range(num_episodes):
    estado = np.random.randint(0, len(estados))  # Estado inicial aleatorio

    while True:
        # Tomar una acción: exploración o explotación
        if np.random.rand() < epsilon:
            accion = np.random.randint(0, len(acciones))  # Acción aleatoria
        else:
            accion = np.argmax(Q[estado])

        # Obtener la recompensa y el próximo estado
        recompensa = recompensas[estado, accion]
        proximo_estado = (estado + 1) % len(estados)  # Transición determinística

        # Actualizar la matriz Q con la fórmula de Q-learning
        Q[estado, accion] = Q[estado, accion] + alpha * (recompensa + gamma * np.max(Q[proximo_estado, :]) - Q[estado, accion])

        # Actualizar el estado actual
        estado = proximo_estado

        if estado == 0:  # Si se alcanza el estado final (A), terminar el episodio
            break



In [152]:
# Imprimir la matriz Q resultante
print("Tabla Q:")
print(Q)

# Aplicar la función softmax para obtener las probabilidades
probs = np.exp(Q) / np.sum(np.exp(Q), axis=1, keepdims=True)

# Obtener el índice de la acción con mayor probabilidad en cada fila
acciones_maximas = np.argmax(probs, axis=1)
acciones_minimas = np.argmin(probs, axis=1)

# Obtener los valores de probabilidad para cada acción en cada fila
probabilidades_acciones = np.round(probs * 100, 1)

# Definir los estados y acciones correspondientes
estados = ['A', 'B', 'C', 'D', 'E']
acciones = ['column 1', 'column 2', 'column 3', 'column 4']

# Imprimir los resultados
for estado, acciones_probabilidades, acciones_maximas in zip(estados, probabilidades_acciones, acciones_maximas):
    print(f"\n Estado {estado}:")
    for accion, probabilidad in zip(acciones, acciones_probabilidades):
        print(f"  Probabilidad para la acción {accion}: {probabilidad:.1f}%")
    print("#" * 25)
    print(f"  Camino a tomar: {acciones[acciones_maximas]}")
    print("#" * 25)

Tabla Q:
[[5.54082769 4.18318599 4.03202617 5.05801242]
 [6.25179099 4.08216331 5.09644718 3.61872469]
 [4.47736072 6.14525176 3.84434617 5.1004    ]
 [4.94507566 5.54759609 6.22220191 3.64638332]
 [3.18287402 3.95123471 5.96179506 4.63027959]]

 Estado A:
  Probabilidad para la acción column 1: 47.7%
  Probabilidad para la acción column 2: 12.3%
  Probabilidad para la acción column 3: 10.6%
  Probabilidad para la acción column 4: 29.4%
#########################
  Camino a tomar: column 1
#########################

 Estado B:
  Probabilidad para la acción column 1: 66.6%
  Probabilidad para la acción column 2: 7.6%
  Probabilidad para la acción column 3: 21.0%
  Probabilidad para la acción column 4: 4.8%
#########################
  Camino a tomar: column 1
#########################

 Estado C:
  Probabilidad para la acción column 1: 11.5%
  Probabilidad para la acción column 2: 61.0%
  Probabilidad para la acción column 3: 6.1%
  Probabilidad para la acción column 4: 21.4%
############

In [153]:

print("Tabla Q:")
print(Q)

# Utilizar la política aprendida para tomar decisiones
def tomar_decision(estado):
    return np.argmax(Q[estado])

# Ejemplo de uso: Tomar decisiones desde el estado inicial
estado_inicial = 3  # Puedes cambiar esto con el estado desde el que quieres empezar
print(f"\nTomar decisiones desde el estado {estados[estado_inicial]}:")
for _ in range(5):  # Tomar decisiones durante 5 pasos
    accion_elegida = tomar_decision(estado_inicial)
    print(f"Desde {estados[estado_inicial]}, tomar acción: {acciones[accion_elegida]}")
    estado_inicial = (estado_inicial + 1) % len(estados)


Tabla Q:
[[5.54082769 4.18318599 4.03202617 5.05801242]
 [6.25179099 4.08216331 5.09644718 3.61872469]
 [4.47736072 6.14525176 3.84434617 5.1004    ]
 [4.94507566 5.54759609 6.22220191 3.64638332]
 [3.18287402 3.95123471 5.96179506 4.63027959]]

Tomar decisiones desde el estado D:
Desde D, tomar acción: column 3
Desde E, tomar acción: column 3
Desde A, tomar acción: column 1
Desde B, tomar acción: column 1
Desde C, tomar acción: column 2
